import Navbar from '../components/Navbar'
import { GoLocation } from "react-icons/go";
import { MdEmail, MdCall } from "react-icons/md";
import Link from 'next/link';
import Footer from '../components/Footer'
import Head from 'next/head'
import { useState } from 'react';
const Contactwebsitedevelopmentservicesinusa = () => {
    const [name, setname] = useState("");
    const [email, setemail] = useState("");
    const [phone, setphone] = useState("");
    const [describeProject, setdescribeProject] = useState("");
    const [companyname, setcompanyName] = useState("");
    const [file, setFile] = useState("")

    async function Submitdata(event) {
        event.preventDefault();
        if (!name || !email || !phone  ||!companyname ||!describeProject) {
            // toast("all fields are required !!");
        } else {
            let item = {
                name,
                email,
                phone,
                companyname,
                describeProject,
                file
            };
            let result = await fetch("https://usedcars.onrender.com/user/addContact",
                {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    body: JSON.stringify(item),
                });
            result = await result.json();
            if (result.success === true) {
                // toast(result.message);
            }
            else {
                // toast('something went wrong')
            }
        }
    }
    return (
        <>
            <Navbar />
            <Head>
                <title>Contact Website Development Services Company in USA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="googlebot" content="noindex" />
                <meta key="robots" content="noindex" />
            </Head>
            <div className='contact-us-page-imge-part'>
                <div className='container'>
                    <div className='contact-title-part'>
                        <h1>Contact Us</h1>
                    </div>
                </div>
            </div>
            <div className='container'>
                <div className='Contact-form-color-part'>
                <form onSubmit={Submitdata}>
                    <div className='contact-form-part'>
                        <h2>Drop Us a Line</h2>
                        <p>Post your requirements here and we will contact you Shortly.</p>
                        <div className='Contact-flex-part'>                    
                            <div className='contact-input-part'>
                                <label >Name</label><br />
                                <input onChange={(e) => setname(e.target.value)} type="text" placeholder='Name' /><br />
                                <label>Email</label><br />
                                <input onChange={(e) => setemail(e.target.value)} type="email" placeholder="Email" /><br />
                                <label>Phone</label><br />
                                <input onChange={(e) => setphone(e.target.value)} type="text" placeholder="Phone" /><br />
                                <label >Company Name</label><br />
                                <input onChange={(e) => setcompanyName(e.target.value)} type="text" placeholder="Company Name" /><br />
                                <label>Describe Your Project</label><br />
                                <textarea onChange={(e) => setdescribeProject(e.target.value)} type="text" placeholder="" />
                            </div>
                            <div className='Contact-from-second-part'>
                                <h3>Tell us a bit more about your project</h3>
                                <p>Post your requirements here and we will contact you Shortly.</p>
                                <div className='Contact-check-part'>
                                    <input type="checkbox" id="vehicle1" name="vehicle1" />
                                    <label>  Web Development</label><br />
                                    <input type="checkbox" id="vehicle2" name="vehicle2" value="Car" />
                                    <label> Software Development</label><br />
                                    <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat" />
                                    <label> Ecommerce Development</label><br />
                                    <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat" />
                                    <label> Wordpress Development</label><br />
                                    <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat" />
                                    <label> React.js Development</label><br />
                                    <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat" />
                                    <label> Node.js Development</label><br />
                                    <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat" />
                                    <label> React Native Development</label><br />
                                    <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat" />
                                    <label> Laravel Development</label><br />
                                    <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat" />
                                    <label> React Native Development</label><br />
                                </div>
                            </div>
                        </div>
                        <div className='Contact-button-part'>
                            <button>Submit</button>
                        </div>
                    </div>
                    <div className='contact-second-flex-part'>
                        <div className='contact-location-part'>
                            <h3><Link href=""><GoLocation />2348 Stephen Robert Ln, Manteca, CA 95337, USA</Link></h3>
                            <h3><Link href="tel:+1(209)226-445"><MdCall />+1(209)226-445</Link></h3>
                            <h3><Link href=""><MdEmail />manjitcheema455@gmail.com</Link></h3>
                        </div>
                        <div className='contact-map'>
                            <div className="mapouter"><div className="gmap_canvas"><iframe className="gmap_iframe" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%&amp;height=100%&amp;hl=en&amp;q=2348 Stephen Robert of Ln, Manteca, CA 95337, USA&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed" ></iframe></div></div>
                            <div style={{ height: "50px", width: "100%" }}>
                            </div>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
            <Footer />
        </>
    )
}
export default Contactwebsitedevelopmentservicesinusa;