import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Link from 'next/link'
import { TbCircleDotted } from "react-icons/tb";
const inter = Inter({ subsets: ['latin'] })
import { useState } from 'react'
import { FaSignal, FaRegHandshake } from "react-icons/fa";
import { AiOutlineStar } from "react-icons/ai";
import { FaWordpress, FaReact, FaNodeJs, FaWix } from "react-icons/fa";
import { SiNextdotjs } from "react-icons/si";
export default function Home() {
  const [one, setOne] = useState(true)
  const [two, setTwo] = useState(false)
  const [three, setThree] = useState(false)
  const [four, setfour] = useState(false)
  const [five, setfive] = useState(false);
  const [six, setsix] = useState(false);
  const [changed1, setchanged1] = useState('four-home-page-pricing');
  const [changed2, setchanged2] = useState('');
  const [changed3, setchanged3] = useState('');
  const [changed4, setchanged4] = useState('');
  const [changed5, setchanged5] = useState('');
  const [changed6, setchanged6] = useState('');
  const handleone = () => {
    setOne(!one)
    setTwo(false)
    setThree(false)
    setfour(false)
    setfive(false)
    setsix(false)
    setchanged1('four-home-page-pricing')
    setchanged2('')
    setchanged3('')
    setchanged4('')
    setchanged5('')
    setchanged6('')
  }
  const handletwo = () => {
    setTwo(!two)
    setThree(false)
    setOne(false)
    setfour(false)
    setfive(false)
    setsix(false)
    setchanged1('')
    setchanged2('four-home-page-pricing')
    setchanged3('')
    setchanged4('')
    setchanged5('')
    setchanged6('')
  }
  const handlethree = () => {
    setThree(!three)
    setOne(false)
    setTwo(false)
    setfour(false)
    setfive(false)
    setsix(false)
    setchanged1('')
    setchanged2('')
    setchanged3('four-home-page-pricing')
    setchanged4('')
    setchanged5('')
    setchanged6('')
  }
  const handlefour = () => {
    setOne(false)
    setTwo(false)
    setThree(false)
    setfour(!four)
    setfive(false)
    setsix(false)
    setchanged1('')
    setchanged2('')
    setchanged3('')
    setchanged4('four-home-page-pricing')
    setchanged5('')
    setchanged6('')
  }
  const handlefive = () => {
    setOne(false)
    setTwo(false)
    setThree(false)
    setfour(false)
    setfive(!five)
    setchanged1('')
    setchanged2('')
    setchanged3('')
    setchanged4('')
    setchanged5('four-home-page-pricing')
    setchanged6('')
  }
  const handlesix = () => {
    setOne(false)
    setTwo(false)
    setThree(false)
    setfour(false)
    setfive(false)
    setsix(!six)
    setchanged1('')
    setchanged2('')
    setchanged3('')
    setchanged4('')
    setchanged5('')
    setchanged6('four-home-page-pricing')
  }
  const [name,setName] =useState("");
  const [email,setEmail] =useState("");
  const [phone,setphone] =useState("");
  const [message,setMessage] =useState("");
  const [file ,setFile] =useState("")
  async function Submitdata(event) {
    event.preventDefault();
    if (!name || !email|| !phone || !message ) {
        // toast("all fields are required !!");
    } else {
        let item = {
            name,
            email,
            phone,
            message,
            file
        };
        let result = await fetch("https://usedcars.onrender.com/user/addHome",
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify(item),
            });
        result = await result.json();
        if (result.success === true) {
            // toast(result.message);
        }
        else {
            // toast('something went wrong')
        }
    }
}
  return (
    <>
      <Navbar />
      <Head>
        <title>Website Development Services Company in USA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="googlebot" content="noindex" />
        <meta key="robots" content="noindex" />
        {/* <link rel="icon" type="image/png" sizes="16x16" href="/Digital MarketingCoursesinChandigarh.png"/> */}
      </Head>
      <div className='index-web-first-image-part'>
        <div className='container'>
          <div className='index-web-title-part'>
            <h1>Let’s build a great website Together.</h1>
            <p>We can bring your web design vision and ideas to life through innovative custom design for your business. We work on hundreds of websites a year, and bring unique insight from our deep experience.</p>
            <button><Link href="">Get Started Now</Link></button>
          </div>
        </div>
      </div>
      <div className='index-web-second-color-part'>
        <div className='container'>
          <div className='index-web-first-flex-part'>
            <div className='index-web-logo-part'>
              <Image src="/Badg.svg" width="150" height="200" alt="" />
              <Image src="/Badg.svg" width="150" height="200" alt="" />
              <Image src="/Badg.svg" width="150" height="200" alt="" />
              <Image src="/Badg.svg" width="150" height="200" alt="" />
            </div>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='index-web-three-flex-part'>
          <div className='index-web-three-part'>
            <h2>
              <span>350+  </span>
              Web Design Case Studies</h2>
            <p>Coalition’s web design team has built hundreds of world class websites with very high returns on investment. We specialize in helping businesses build eCommerce and lead generation focused websites.</p>
            <div className='index-web-img-flex-part'>
              <div className='index-web-small-part'>
                <Image src="/Small.svg" width="20" height="20" alt="" />
                <h3>Design</h3>
              </div>
              <div className='index-web-small-part'>
                <Image src="/Content.svg" width="20" height="20" alt="" />
                <h3>Content Management</h3>
              </div>
            </div>

            <div className='index-web-img-flex-part'>
              <div className='index-web-small-part'>
                <Image src="/Development.svg" width="20" height="20" alt="" />
                <h3>Development</h3>
              </div>
              <div className='index-web-small-part'>
                <Image src="/Workflow.svg" width="20" height="20" alt="" />
                <h3>Workflow Systems</h3>
              </div>
            </div>

            <div className='index-web-img-flex-part'>
              <div className='index-web-small-part'>
                <Image src="/eCommerce.svg" width="20" height="20" alt="" />
                <h3>E-commerce</h3>
              </div>
              <div className='index-web-small-part'>
                <Image src="/CustomApps.svg" width="20" height="20" alt="" />
                <h3>Custom Apps</h3>
              </div>
            </div>
          </div>
          <form onSubmit={Submitdata}>
          <div className='index-web-form-color-part'>
              <div className='index-web-form-part'>
                <h3>GET A FREE PROJECT PLAN AND SCOPE NOW</h3>
                <div className='index-web-form2-part'>
                  <input onChange={(e) => setName(e.target.value)} type="text" placeholder='Name*' /><br />
                  <input onChange={(e) => setEmail(e.target.value)} type="email" placeholder="Email*" /><br />
                  <input onChange={(e) => setphone(e.target.value)} type="text" placeholder='Phone*' /><br />
                  <input onChange={(e) => setMessage(e.target.value)} type="text" placeholder='Message*' />
                </div>
                <div className='index-web-checkbox-flex'>
                  <div className='index-input'>
                    <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike" />
                    <label>Im not a robot</label>
                  </div>

                  <div className='index-web-logo2-part'>
                    <Image src="/log.png" width="20" height="20" alt='' />
                  </div>
                </div>
                <div className='index-web-checkbox-input-part'>
                  <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike" />
                  <label>I would like to receive expert digital growth tips from Coalition Technologies</label><br />
                </div>
                <button>Submit</button>
              </div>
          </div>
          </form>
        </div>
      </div>
      <div className='index-web-center-color-part'>
        <div className='container'>
          <div className='index-web-center-title-part'>
            <h3>What Kind of Website Do You Need?</h3><p>We have over 200 team members specializing in diverse platforms, coding languages, frameworks, and industries. Whether you need a website for an ecommerce business, local lead generation, a custom application, or informational and entertainment purposes, we can help.</p>
          </div>
        </div>
      </div>
      <div className='index-web-four-color-part'>
        <div className='container'>
          <div className='index-four-flex-part'>
            <div className='index-four-title-part'>
              <h3>READ ABOUT HOW COALITION’S ECOMMERCE SITE MADE A BIG IMPACT FOR PINK LILY</h3>
              <p>This fashion boutique came to Coalition because although they had a social media following, they were not seeing the revenue results they were looking for. We took over full online marketing including web development, Search Engine Optimization (SEO), Pay Per Click (PPC), paid social media, and email marketing. In their first year with us, this fashion retailer generated $2.5 million in revenue while spending only $100,000 on our services.</p>
              <button><Link href="/">SEE CASE STUDY</Link></button>
            </div>
            <div className='index-four-image-part'>
              <Image src="/pink.webp" width="300" height="200" alt='' />
            </div>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='index-web-five-part'>
          <h2>WORLD-CLASS WEBSITE DESIGN AND DEVELOPMENT</h2>
          <div className='index-web-five-flex-part'>
            <div className='index-web-five2-part'>
              <p>Your website design and development critically defines your online presence. Even the most basic improvements in your website can have far-reaching effects on your success in the marketplace.</p>
              <div className='index-web-five-second-flex-part'>
                <div className='index-web-five-imge-part'>
                  <Image src="/world.webp" width="250" height="200" alt='' />
                </div>
                <div className='index-web-five-title2-part'>
                  <p>Businesses can no longer get by with a simple but poorly optimized website. As the web has evolved, customers have become progressively savvier and choose who to do business with based on a business’s digital presence.</p>
                </div>
              </div>
              <p>Coalition Technologies has succeeded and out-performed other web design companies for the past decade by providing a better service that delivers superior outcomes to our clients.</p>
            </div>

            <div className='index-web-five-title-part'>
              <p>With over 600 client case studies ranging from websites for dentists to websites for fashion ecommerce brands, our breadth of experience and repeated ability to drive positive outcomes is unrivaled in the web design industry.</p>
              <p>Our professional Digital Strategists first work with you to develop a scope of work that reflects best practices for your industry and also address your specific business needs. Our project managers, designers, developers, and QA team take that website scope and efficiently execute on it, all while educating you, involving you, and keeping you up to date on our progress.</p>
              <p>Hundreds of clients have raved about our services on Clutch, Google, Facebook, and more. Contact us today and our expert team will review your account and provide you with a strategy, timeline, and forecast that includes a competitor strategy review for free. We can get you started immediately, so call us right now at </p>
            </div>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='index-web-service-flex-part'>
          <div className='index-web-web-servic-first-box-part'>
            <h4><FaWordpress /></h4>
            <h2>Wordpress Web Development</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <button><Link href="/Wordpresswebsitedevelopmentservicesinusa">Read More</Link></button>
          </div>
          <div className='index-web-web-servic-first-box-part'>
            <Image src="/sofi.png" width="200" height="70" alt='' />
            <h2>Shopify web development</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <button><Link href="/ShopifywebsitedevelopmentservicesinUSA">Read More</Link></button>
          </div>
          <div className='index-web-web-servic-first-box-part'>
            <h4><FaReact /></h4>
            <h2>React.js</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <button><Link href="/Reactwebsitedevelopmentservicesinusa">Read More</Link></button>
          </div>
          <div className='index-web-web-servic-first-box-part'>
            <h4><SiNextdotjs /></h4>
            <h2>Next.js</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <button><Link href="/Nextwebsitedevelopmentservicesinusa">Read More</Link></button>
          </div>
          <div className='index-web-web-servic-first-box-part'>
            <h4><FaNodeJs /></h4>
            <h2>Node.js</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <button><Link href="/Nodewebsitedevelopmentservicesinusa">Read More</Link></button>
          </div>
          <div className='index-web-web-servic-first-box-part'>
            <h4><FaWix /></h4>
            <h2>Wix</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <button><Link href="/Wixwebsitedevelopmentservicesinusa">Read More</Link></button>
          </div>
          <div className='index-web-web-servic-first-box-part'>
            <Image src="/kajabi.png" width="200" height="70" alt='Kajabi' />
            <h2>Kajabi</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
            <button><Link href="/Kajabiwebsitedevelopmentservicesinusa">Read More</Link></button>
          </div>
        </div>
      </div>
      <div className='index-web-six-color-part'>
        <div className='container'>
          <div className='index-web-six-flex-part'>
            <div className='index-web-six-part'>
              <Image src="/googlepartner.png" width="150" height="100" alt='' />
            </div>
            <div className='index-web-six-part'>
              <Image src="/commerce.png" width="150" height="100" alt='' />
            </div>
            <div className='index-web-six-part'>
              <Image src="/shopify.jpg" width="150" height="100" alt='' />
            </div>
            <div className='index-web-six-part'>
              <Image src="/winner.png" width="150" height="100" alt='' />
            </div>
            <div className='index-web-six-part'>
              <Image src="/seopartner.png" width="150" height="100" alt='' />
            </div>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='index-web-seven-part'>
          <h3>What Is The Best CMS For You?</h3>
          <p>Coalition actively reviews and evaluates the effectiveness of leading website content management systems. As your website design and development company, we expect our expertise to help guide you to the right website platform selection.</p>
        </div>
      </div>
      <div className='index-web-eight-color-part'>
        <div className='container'>
          <div className='index-web-eight-flex-part'>
            <div className='index-web-eight-img-part'>
              <Image src="/paypal.webp" width="190" height="100" alt='' />
            </div>
            <div className='index-web-eight-title-part'>
              <h3>DISCOVER THE BIGCOMMERCE WEBSITE DESIGN AND DEVELOPMENT WE DID FOR PAYPAL</h3>
              <p>When you’re a brand synonymous with ecommerce and online transacting, your choice in partners is critical. PayPal chose Coalition for its BigCommerce Enterprise store builds after an exhaustive vetting process that compared some of the ecommerce industry’s leading agencies. Our knowledge of the SaaS ecommerce market, BigCommerce, and our ability to provide extensive custom development to support the brand’s need were all winning factors. The mobile friendly, content rich ecommerce site stands out from typical ecommerce experience and captures the PayPal brand wonderfully.</p>
              <button>
                <Link href="">SEE CASE STUDY</Link>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='index-web-nine-part'>
          <h3>What Our Clients Are Saying</h3>
        </div>
        <div className='index-web-nine-flex-part'>
          <div className='index-web-nine-first-part'>
            <div className='index-web-nine-img-part'>
              <Image src="/Chris.webp" width="190" height="100" alt='' />
              <h6>CHRIS G.</h6>
            </div>
            <p>
              They had a long list of satisfied customers that we could reference. They also delivered and met our goals each time we had a new project. Two years later, the relationship continues to succeed. Coalition Technologies is agile enough to respond to shifting requirements and consistent enough to deliver reliably high-quality results. Their effective communication and quick turnaround times make them a dependable partner. </p>
          </div>
          <div className='index-web-nine-first-part'>
            <div className='index-web-nine-img-part'>
              <Image src="/Chris.webp" width="90" height="30" alt='' />
              <h6>CHRIS G.</h6>
            </div>
            <p>
              I considered myself a small client of Coalition Technologies but I was very impressed that Joel Gross, the owner, personally oversaw the launch of my website re-design. Joel cares very much about the client’s experience and that they are happy. I hold Joel personally in the highest professional regard and would not hesitate to reach out to him on any matter in the future. It’s so rare in today’s world to find somebody so passionate about client happiness and satisfaction.</p>
          </div>
          <div className='index-web-nine-first-part'>
            <div className='index-web-nine-img-part'>
              <Image src="/Chris.webp" width="200" height="100" alt='' />
              <h6>CHRIS G.</h6>
            </div>
            <p>
              It was a pleasure to work with Coalition Technologies. They were really very responsive in their replies and was able to complete the things that I asked in just a few days. I would highly recommend them for your SEO, social media, and website needs. They will surely be able to help you overcome any problems related to your business presence and sales.   </p>
          </div>
        </div>
      </div>
      <div className="index-web-ten-color-part">
        <div className="container">
          <div className='index-web-ten-contact-part'>
            <p>Call us at <Link href="tel:123-456-7890"> (888) 914-9670</Link>
              <span>Or<Link href="">Email Us</Link></span></p>
          </div>
        </div>
      </div>
      <div className='index-project-color-part'>
        <div className='container'>
          <div className='index-web-Project-part'>
            <h2>Featured Projects</h2>
            <div className='index-web-Project-flex-part'>
              <div className='index-web-Project-title-part'>
                <Image src="/project.webp" width="400" height="100" alt='' />
                <h4>PINK LILY</h4>
                <p>See how our web development and SEM services helped Pink Lily generate $2.5 million in revenue in the first year of working with us.</p>
                <button>SEE CASE STUDY</button>
              </div>
              <div className='index-web-Project-title-part'>
                <Image src="/nativ.webp" width="400" height="100" alt='' />
                <h4>NATIVE UNION</h4>
                <p>Learn how our website redesign helped Native Union increase revenue by 20% month over month and organic traffic by 58% in just six months.</p>
                <button>SEE CASE STUDY</button>
              </div>
            </div>
          </div>
          <div className='index-web-Project-button-part'>
            <button>
              <Link href="">VIEW MORE WEB DESIGN CASE STUDIES</Link>
            </button>
          </div>
        </div>
      </div>
      <div className='index-web-work-color-part'>
        <div className='container'>
          <div className='index-web-work-title-part'>
            <h3>Our Work Includes 600+ Websites Built</h3>
          </div>
          <div className='index-web-work-flex-part'>
            <div className='index-web-work-image-part'>
              <Image src="/WebDesign.svg" width="150" height="100" alt='' />
              <h4>
                <Link href="">WEB DESIGN</Link>
              </h4>
            </div>
            <div className='index-web-work-image-part'>
              <Image src="/Develo.svg" width="150" height="100" alt='' />
              <h4>
                <Link href="">WEB DEVELOPMENT</Link>
              </h4>
            </div>
            <div className='index-web-work-image-part'>
              <Image src="/Branding.svg" width="150" height="100" alt='' />
              <h4>
                <Link href="">BRANDING</Link>
              </h4>
            </div>
            <div className='index-web-work-image-part'>
              <Image src="/SEO.svg" width="150" height="100" alt='' />
              <h4>
                <Link href="">SEO</Link>
              </h4>
            </div>
            <div className='index-web-work-image-part'>
              <Image src="/Ecommerce.svg" width="150" height="100" alt='' />
              <h4>
                <Link href="">E-commerce</Link>
              </h4>
            </div>
          </div>
          <div className='index-web-work-button-part'>
            <button>
              <Link href="">READ OUR CASE STUDIES BY SERVICE</Link>
            </button>
          </div>
        </div>
      </div>
      <div className='index-web-Sales-color-part'>
        <div className='container'>
          <div className='index-web-Sales-title-part'>
            <h3>600+ Case Studies Driving Sales</h3>
          </div>
          <div className='index-web-Sales-flex-part'>
            <div className='index-web-Sales-image-part'>
              <Image className={changed1} onClick={handleone} src="/district.webp" width="150" height="100" alt='' />
            </div>
            <div className='index-web-Sales-image-part'>
              <Image className={changed2} onClick={handletwo} src="/bpn.webp" width="150" height="100" alt='' />
            </div>
            <div className='index-web-Sales-image-part'>
              <Image className={changed3} onClick={handlethree} src="/qspray.webp" width="150" height="100" alt='' />
            </div>
            <div className='index-web-Sales-image-part'>
              <Image className={changed4} onClick={handlefour} src="/watch.png" width="150" height="100" alt='' />
            </div>
            <div className='index-web-Sales-image-part'>
              <Image className={changed5} onClick={handlefive} src="/peak.webp" width="150" height="100" alt='' />
            </div>
            <div className='index-web-Sales-image-part'>
              <Image lassName={changed6} onClick={handlesix} src="/krav.webp" width="150" height="100" alt='' />
            </div>
          </div>
          {one ?
            <div>
              <div className='index-web-Sales-popup-part'>
                <div className='index-web-Sales-popup-images'>
                  <Image src="/highlights.webp" width="150" height="100" alt='' />
                  <h3>Increased traffic by nearly 200%.</h3>
                  <p>District Clothing, a fashion basics retailer, was having a difficult time getting the brand recognition and traffic they deserved due to a highly competitive SEO landscape. They came to Coalition in hopes of bringing more traffic to their website and generating more revenue.</p>
                  <p>After designing and developing a new WordPress and Nexternal ecommerce website for them, we launched aggressive SEO and PPC campaigns that resulted in an increase in traffic to the brand’s website by nearly 200%. Their site ranked alongside major multinational brands in ideal search results, and their revenue increased in tandem with that growth.</p>
                </div>
              </div>
            </div>
            : ""}
          {two ?
            <div>
              <div className='index-web-Sales-popup-part'>
                <div className='index-web-Sales-popup-images'>
                  <Image src="/highlights.webp" width="150" height="100" alt='' />
                  <h3>Increased traffic by nearly 200%.</h3>
                  <p>District Clothing, a fashion basics retailer, was having a difficult time getting the brand recognition and traffic they deserved due to a highly competitive SEO landscape. They came to Coalition in hopes of bringing more traffic to their website and generating more revenue.</p>
                  <p>After designing and developing a new WordPress and Nexternal ecommerce website for them, we launched aggressive SEO and PPC campaigns that resulted in an increase in traffic to the brand’s website by nearly 200%. Their site ranked alongside major multinational brands in ideal search results, and their revenue increased in tandem with that growth.</p>
                </div>
              </div>
            </div>
            : ""}
          {three ?
            <div>
              <div className='index-web-Sales-popup-part'>
                <div className='index-web-Sales-popup-images'>
                  <Image src="/highlights.webp" width="150" height="100" alt='' />
                  <h3>Increased traffic by nearly 200%.</h3>
                  <p>District Clothing, a fashion basics retailer, was having a difficult time getting the brand recognition and traffic they deserved due to a highly competitive SEO landscape. They came to Coalition in hopes of bringing more traffic to their website and generating more revenue.</p>
                  <p>After designing and developing a new WordPress and Nexternal ecommerce website for them, we launched aggressive SEO and PPC campaigns that resulted in an increase in traffic to the brand’s website by nearly 200%. Their site ranked alongside major multinational brands in ideal search results, and their revenue increased in tandem with that growth.</p>
                </div>
              </div>
            </div>
            : ""}
          {four ?
            <div>
              <div className='index-web-Sales-popup-part'>
                <div className='index-web-Sales-popup-images'>
                  <Image src="/highlights.webp" width="150" height="100" alt='' />
                  <h3>Increased traffic by nearly 200%.</h3>
                  <p>District Clothing, a fashion basics retailer, was having a difficult time getting the brand recognition and traffic they deserved due to a highly competitive SEO landscape. They came to Coalition in hopes of bringing more traffic to their website and generating more revenue.</p>
                  <p>After designing and developing a new WordPress and Nexternal ecommerce website for them, we launched aggressive SEO and PPC campaigns that resulted in an increase in traffic to the brand’s website by nearly 200%. Their site ranked alongside major multinational brands in ideal search results, and their revenue increased in tandem with that growth.</p>
                </div>
              </div>
            </div>
            : ""}
          {five ?
            <div>
              <div className='index-web-Sales-popup-part'>
                <div className='index-web-Sales-popup-images'>
                  <Image src="/highlights.webp" width="150" height="100" alt='' />
                  <h3>Increased traffic by nearly 200%.</h3>
                  <p>District Clothing, a fashion basics retailer, was having a difficult time getting the brand recognition and traffic they deserved due to a highly competitive SEO landscape. They came to Coalition in hopes of bringing more traffic to their website and generating more revenue.</p>
                  <p>After designing and developing a new WordPress and Nexternal ecommerce website for them, we launched aggressive SEO and PPC campaigns that resulted in an increase in traffic to the brand’s website by nearly 200%. Their site ranked alongside major multinational brands in ideal search results, and their revenue increased in tandem with that growth.</p>
                </div>
              </div>
            </div>
            : ""}
          {six ?
            <div>
              <div className='index-web-Sales-popup-part'>
                <div className='index-web-Sales-popup-images'>
                  <Image src="/highlights.webp" width="150" height="100" alt='' />
                  <h3>Increased traffic by nearly 200%.</h3>
                  <p>District Clothing, a fashion basics retailer, was having a difficult time getting the brand recognition and traffic they deserved due to a highly competitive SEO landscape. They came to Coalition in hopes of bringing more traffic to their website and generating more revenue.</p>
                  <p>After designing and developing a new WordPress and Nexternal ecommerce website for them, we launched aggressive SEO and PPC campaigns that resulted in an increase in traffic to the brand’s website by nearly 200%. Their site ranked alongside major multinational brands in ideal search results, and their revenue increased in tandem with that growth.</p>
                </div>
              </div>
            </div>
            : ""}
        </div>
      </div>
      <div className='container'>
        <div className='index-web-Design-part'>
          <h3>Web Design Matters</h3>
          <p>Web Design impacts how users perceive your brand, and you only get one chance to make that first impression. Great web design will provide users with an intuitive, attractive experience across all platforms while informing them about your brand and increasing your conversion rate.</p>
        </div>
      </div>
      <div className='container'>
        <div className='index-web-design-flex'>
          <div className='index-web-desin-part'>
            <h4>RESPONSIVE DESIGN</h4>
            <p>Mobile users account for more than half of all website traffic and that percentage keeps rising. To increase conversions and maintain your brand authority, we implement responsive web designs that will adjust to any screen size or platform for the best user experience.</p>
          </div>
          <div className='index-web-design-imge-part'>
            <Image src="/Responsivedesign.webp" width="150" height="100" alt='' />
          </div>
        </div>
        <div className='index-web-design-flex'>
          <div className='index-web-design-imge-part'>
            <Image src="/Integratedmarketing.webp" width="150" height="100" alt='' />
          </div>
          <div className='index-web-desin-part'>
            <h4>INTEGRATED MARKETING</h4>
            <p>Successful web design includes integrated marketing that targets your optimal user base. Our ability to integrate better tracking, analytics, SEO, SEM, social, and email marketing into your website build guarantees lower bounce rates and considerably more conversions.</p>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='index-web-marketing-box-flex-part'>
          <div className='index-web-market-first-box-part'>
            <h4><TbCircleDotted /></h4>
            <h3>INTEGRATED MARKETING</h3>
            <p>Our team of 180+ has expertise in SEO, PPC, web design and development with a 600+ successful client track record.</p>
          </div>
          <div className='index-web-market-first-box-part'>
            <h4><FaSignal /></h4>
            <h3>PROVEN RESULTS</h3>
            <p>Our checklists, systems, and processes lead to consistent results across our clients.</p>
          </div>
          <div className='index-web-market-first-box-part'>
            <h4><FaRegHandshake /></h4>
            <h3>EXPERT SUPPORT</h3>
            <p>Our world class team is headquartered in Los Angeles and are able to resolve any issue.</p>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className="index-web-Ecommerce-flex-part">
          <div className='index-web-Ecommerce-image-part'>
            <Image src="/services.webp" width="500" height="100" alt='' />
          </div>
          <div className='index-Ecommerce-title-part'>
            <h3>Were eCommerce Website Design Pros</h3>
            <p>Online sales are booming as <strong>US consumers will spend over $930 billion on eCommerce websites</strong> this year, up 18% year-over-year. Although this seems like an extremely high number, it’s still only 15% of total retail sales, meaning online sales still have a huge growth curve. While modern business and upstarts have made the transition, many traditional businesses have yet to do so, especially in the B2B space. At OuterBox, our website design services help to move your business forward, giving you the website technology needed to sell basic products online or complex custom services. We also specialize in ERP integrations, API data integrations, and other services needed for enterprise-level businesses. We’ve been development experts since 2004, so if you’re in the market for a new website, look no further. </p>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='index-web-digital-flex-part'>
          <div className='index-web-digital-first-part'>
            <h3>What High-End Web Design Can Do for You</h3>
            <p>In today’s competitive marketplace, an adequate website just won’t cut it. Online shoppers have become accustomed to responsive websites that are easy to use, appealing to the eye, and fast. A recent study showed that the average user would click off a website that took longer than 3 seconds to load. Three seconds! If your website isn’t meeting or exceeding a user’s expectations, you’re going to lose authority, trust, and especially revenue. However, a well-designed website can define your brand, engage your audience, and drive your sales beyond expectation.</p>
          </div>
          <div className='index-web-digital-second-part'>
            <Image src="/High.webp" width="150" height="100" alt='' />

          </div>
        </div>
        <div className='index-web-digital-flex-part'>
          <div className='index-web-digital-first-part'>
            <h3>What Coalition Technologies Can Do for You</h3>
            <p>Coalition Technologies has built an expert team of web designers and developers who are at the forefront of the industry. Through innovation and continuous learning, we are able to stay on top of an ever-changing landscape and deliver cutting-edge designs that put your website a step ahead of the competition.</p>
            <p>With over 600 successful client case studies, Coalition can prove our results. We can show you how we increase traffic, reduce bounce rates, and drive revenue. Take a look at our case studies and see how our web design services have generated hundreds of millions of dollars for our clients. We will do the same for you.</p>
          </div>
          <div className='index-web-digital-second-part'>
            <Image src="/Business.webp" width="150" height="100" alt='' />
          </div>
        </div>
      </div>
      <div className='index-web-review-color-part'>
        <div className='container'>
          <div className='index-web-reviews-flex-part'>
            <div className='index-web-reviews-first-part'>
              <Image src="/Google.png" width="90" height="30" alt='' /><br />
              <AiOutlineStar />
              <AiOutlineStar />
              <AiOutlineStar />
              <h4>100+ reviews</h4>
            </div>
            <div className='index-web-reviews-first-part'>
              <Image src="/Facebook.png" width="90" height="30" alt='' /><br />
              <AiOutlineStar />
              <AiOutlineStar />
              <AiOutlineStar />
              <h4>70+ reviews</h4>
            </div>
            <div className='index-web-reviews-first-part'>
              <Image src="/clutch.png" width="90" height="30" alt='' /><br />
              <AiOutlineStar />
              <AiOutlineStar />
              <AiOutlineStar />
              <h4>20+ reviews</h4>
            </div>
          </div>
        </div>
      </div>
      <div className='index-web-Coalition-color-part'>
        <div className='container'>
          <div className='index-web-Coalition-title-part'>
            <h4>Work with Coalition</h4>
            <p>If you want to future-proof your website and generate more revenue, contact us today. Our exceptional team of web designers and developers will review your website and provide you with an analysis, strategy, and timeline that includes a competitor strategy review for free. We can get you started immediately, so call us right now at </p>
          </div>
        </div>
      </div>
      <Footer />
    </>
  )
}
