import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { useState } from 'react'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
import { FaWordpress, FaDesktop, FaRegImage, FaSignal, FaThList, FaReact } from "react-icons/fa";
 const Portfoliowebsitedevelopmentservicesinusa =()=> {
  const [changed1, setchanged1] = useState('four-home-page-pricing');
  const [changed2, setchanged2] = useState('');
  const [changed3, setchanged3] = useState('');
  const [changed4, setchanged4] = useState('');
  const [changed, setchanged5] = useState('');
  const [one, setOne] = useState(true)
  const [two, setTwo] = useState(false)
  const [three, setThree] = useState(false)
  const [four, setfour] = useState(false)
  const [five, setfive] = useState(false);

  const handleone = () => {
    setOne(!one)
    setTwo(false)
    setThree(false)
    setfour(false)
    setchanged1('four-home-page-pricing')
    setchanged2('')
    setchanged3('')
    setchanged4('')
  }
  const handletwo = () => {
    setTwo(!two)
    setThree(false)
    setOne(false)
    setfour(false)
    setchanged1('')
    setchanged2('four-home-page-pricing')
    setchanged3('')
    setchanged4('')
  }
  const handlethree = () => {
    setThree(!three)
    setOne(false)
    setTwo(false)
    setfour(false)
    setchanged1('')
    setchanged2('')
    setchanged3('four-home-page-pricing')
    setchanged4('')
  }
  const handlefour = () => {
    setOne(false)
    setTwo(false)
    setThree(false)
    setfour(!four)
    setchanged1('')
    setchanged2('')
    setchanged3('')
    setchanged4('four-home-page-pricing')
  }
  const handlefive = () => {
    setfive(!five)
  }
  return (
    <>
      <Navbar />
      <Head>
        <title>Portfolio Website Development Services Company in USA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="googlebot" content="noindex" />
        <meta key="robots" content="noindex" />
      </Head>
      <div className='Portfolio-first-image-part'>
        <div className='container'>
          <div className=' Portfolio-title-part'>
            <h1>Our Portfolio</h1>
          </div>
        </div>
      </div>
      <div className='container'>
        <div className='Portfolio-first-flex-part'>
          <div className='Portfolio-first-box-part'>
            <button className={changed1} onClick={handletwo}>  <FaRegImage /> All</button>
          </div>
          <div className='Portfolio-first-box-part'>
            <button className={changed2} onClick={handletwo}>  <FaWordpress />    WordPress</button>
          </div>
          <div className='Portfolio-first-box-part'>
            <button className={changed3} onClick={handleone}> <FaSignal /> SEO</button>
          </div>
          <div className='Portfolio-first-box-part'>
            <button className={changed4} onClick={handlefour}> <FaDesktop /> wix</button>
          </div>
          <div className='Portfolio-first-box-part'>
            <button className={changed3} onClick={handlethree} >Clickfunnels</button>
          </div>
          <div className='Portfolio-first-box-part'>
            <button className={changed3} onClick={handlethree}> <FaThList />Kajabi</button>
          </div>
          <div className='Portfolio-first-box-part'>
            <button className={changed3} onClick={handlethree}> <FaReact /> ReactJS</button>
          </div>
        </div>
      </div>
      {one ?
        <div>
          <div className='container'>
            <div className='Portfolio-first-title-part'>
              <h2>Search Engine
                <span>   Optimization</span> </h2>
            </div>
            <div className='Portfolio-second-flex-part'>
              <div className='Portfolio-box-first-part'>
                <Image src="/new.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>New Baby N You</h3>
                  <h2> <Link href="/">https://newbabynyou.com/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/entrance.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Entrance Matting</h3>
                  <h2> <Link href="/">https://entrancemattingireland.ie/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/dilov.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Dailyovation</h3>
                  <h2><Link href="/">https://dailyovation.com/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/girls.png" width="330" height="250" alt='girls' />
                <div className='Portfolio-title2-part'>
                  <h3>Clarte </h3>
                  <h2><Link href="/">https://www.clarte.co.za/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/fjtravels.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Knocker Ball</h3>
                  <h2><Link href="/">https://www.fjtravels.com/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/knockerball.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Fj Travels</h3>
                  <h2><Link href="/">https://knockerball.com/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/Screen.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Pink Soda Salon</h3>
                  <h2><Link href="/">https://www.pinksodasalon.com/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
        : ""}
      {two ?
        <div>
          <div className='container'>
            <div className='index-three-title-part'>
              <h2>Wordpress <span>  Development</span> </h2>
            </div>
            <div className='index-three-flex-part'>
              <div className="index-wordpress-box-part">
                <Image src="/phone.jpg" width="330" height="200" alt='' />
                <div className='index-wordpress-title-part'>
                  <h3>UiPlay</h3>
                  <h2><Link href="/">https://uiplay.co.za/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="index-wordpress-box-part">
                <Image src="/world.jpg" width="330" height="200" alt='' />
                <div className='index-wordpress-title-part'>
                  <h3>UiWorld</h3>
                  <h2><Link href="/">https://uiworld.co.za/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="index-wordpress-box-part">
                <Image src="/pro.jpg" width="330" height="200" alt='' />
                <div className='index-wordpress-title-part'>
                  <h3>3SixtyHealth</h3>
                  <h2><Link href="/">https://3sixtyhealth.co.za/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="index-wordpress-box-part">
                <Image src="/tyli.jpg" width="330" height="200" alt='' />
                <div className='index-wordpress-title-part'>
                  <h3>3SixtyLife</h3>
                  <h2><Link href="/">https://3sixtylife.co.za/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="index-wordpress-box-part">
                <Image src="/infinm.jpg" width="330" height="200" alt='' />
                <div className='index-wordpress-title-part'>
                  <h3>Infinmobile Solutions</h3>
                  <h2><Link href="/">https://infinmobile.com/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/new.png" width="330" height="200" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>New Baby N You</h3>
                  <h2> <Link href="/">https://newbabynyou.com/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Work</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
        : ""}
      {four ?
        <div>
          <div className='container'>
            <div className='index-wix-Development-title-part'>
              <h2>Wix <span>   Development</span></h2>
            </div>
            <div className='index-wix-Development-flex-part'>
              <div className='index-wix-Development-box-part'>
                <Image src="/infinm.jpg" width="330" height="200" alt='' />
                <div className='index-wordpress-title-part'>
                  <h3>Dr. Aristole</h3>
                  <h2><Link href="/">https://www.draristotle.com/</Link></h2>
                  <div className='Portfolio-wordpress-flex'>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>Backend</p>
                      <p>CMS</p>
                      <p>Type</p>
                    </div>
                    <div className='index-wordpress-part'>
                      <h5>:</h5>
                      <h5>:</h5>
                      <h5>:</h5>
                    </div>
                    <div className='Portfolio-wordpress-title2-part'>
                      <p>--</p>
                      <p>Development</p>
                      <p>Software<br /> Company</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        : ""}
      {three ?
        <div>
          <div className='container'>
            <div className='Portfolio-first-title-part'>
              <h2>Search Engine
                <span>   Optimization</span> </h2>
            </div>
            <div className='Portfolio-second-flex-part'>
              <div className='Portfolio-box-first-part'>
                <Image src="/new.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>New Baby N You</h3>
                  <h2> <Link href="/">https://newbabynyou.com/</Link></h2>
                  <p>Backend</p>
                  <h4>:</h4>
                  <p>PHP</p>
                  <p>CMP</p>
                  <h4>:</h4>
                  <p>WordPress</p>
                  <p>Type</p>
                  <h4>:</h4>
                  <p>Information</p>
                  <p>Work</p>
                  <h4>:</h4>
                  <p>Development & SEO</p>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/entrance.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Entrance Matting</h3>
                  <h2> <Link href="/">https://entrancemattingireland.ie/</Link></h2>
                  <p>Backend</p>
                  <h4>:</h4>
                  <p>PHP</p>
                  <p>CMP</p>
                  <h4>:</h4>
                  <p>WordPress</p>
                  <p>Type</p>
                  <h4>:</h4>
                  <p>E-Commerce</p>
                  <p>Work</p>
                  <h4>:</h4>
                  <p> SEO</p>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/dilov.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Dailyovation</h3>
                  <h2><Link href="/">https://dailyovation.com/</Link></h2>
                  <p>Backend</p>
                  <h4>:</h4>
                  <p>PHP</p>
                  <p>CMP</p>
                  <h4>:</h4>
                  <p>WordPress</p>
                  <p>Type</p>
                  <h4>:</h4>
                  <p>News</p>
                  <p>Work</p>
                  <h4>:</h4>
                  <p>SEO</p>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/girls.png" width="330" height="250" alt='girls' />
                <div className='Portfolio-title2-part'>
                  <h3>Clarte </h3>
                  <h2><Link href="/">https://www.clarte.co.za/</Link></h2>
                  <p>Backend</p>
                  <h4>:</h4>
                  <p>PHP</p>
                  <p>CMP</p>
                  <h4>:</h4>
                  <p>WordPress</p>
                  <p>Type</p>
                  <h4>:</h4>
                  <p>News</p>
                  <p>Work</p>
                  <h4>:</h4>
                  <p>Development & SEO</p>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/fjtravels.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Knocker Ball</h3>
                  <h2><Link href="/">https://www.fjtravels.com/</Link></h2>
                  <p>Backend</p>
                  <h4>:</h4>
                  <p>PHP</p>
                  <p>CMP</p>
                  <h4>:</h4>
                  <p>WordPress</p>
                  <p>Type</p>
                  <h4>:</h4>
                  <p>News</p>
                  <p>Work</p>
                  <h4>:</h4>
                  <p>Development & SEO</p>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/knockerball.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Fj Travels</h3>
                  <h2><Link href="/">https://knockerball.com/</Link></h2>
                  <p>Backend</p>
                  <h4>:</h4>
                  <p>PHP</p>
                  <p>CMP</p>
                  <h4>:</h4>
                  <p>WordPress</p>
                  <p>Type</p>
                  <h4>:</h4>
                  <p>News</p>
                  <p>Work</p>
                  <h4>:</h4>
                  <p>Development & SEO</p>
                </div>
              </div>
              <div className='Portfolio-box-first-part'>
                <Image src="/Screen.png" width="330" height="250" alt='' />
                <div className='Portfolio-title2-part'>
                  <h3>Pink Soda Salon</h3>
                  <h2><Link href="/">https://www.pinksodasalon.com/</Link></h2>
                  <p>Backend</p>
                  <h4>:</h4>
                  <p>PHP</p>
                  <p>CMP</p>
                  <h4>:</h4>
                  <p>WordPress</p>
                  <p>Type</p>
                  <h4>:</h4>
                  <p>News</p>
                  <p>Work</p>
                  <h4>:</h4>
                  <p>Development & SEO</p>
                </div>
              </div>
            </div>

          </div>
        </div>
        : ""}
      <Footer />
    </>
  )
}
export default Portfoliowebsitedevelopmentservicesinusa;