import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { FaCheckCircle } from "react-icons/fa";
const ShopifywebsitedevelopmentservicesinUSA = () => {
    return (
        <>
            <Navbar />
            <Head>
                <title>Shopify Website Development Services Company in USA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="googlebot" content="noindex" />
                <meta key="robots" content="noindex" />
            </Head>
            <div className='Shopify-first-img-part'>
                <div className='container'>
                    <div className='Shopity-flex-part'>
                        <div className='Shopify-first-title-part'>
                            <h1>Shopify Web Design Services</h1>
                        </div>
                        <div className='Shopify-form-color-part'>
                            <div className='Shopify-form-part'>
                                <h2>Quick Contact</h2>
                                <div className='Shopify-form'>
                                    <input type="text" placeholder='Name*' /><br />
                                    <input type="email" placeholder='Email*' /><br />
                                    <input type="text" placeholder='Number*' /><br />
                                    <textarea type="text" placeholder='Message*' />
                                    <div className='Shopify-button'>
                                        <button>Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className='container'>
                <div className='Shopify-title-part'>
                    <h2>Shopify Services</h2>
                    <p>Proven methods of success, put to work on the most flexible ecommerce platform today.</p>
                </div>
                <div className='Shopify-second-flex-part'>
                    <div className='Shofity-first-box-part'>
                        <h3>SHOPIFY DEVELOPMENT & DESIGN</h3>
                        <p>From inception to launch, Coalition Technologies can provide a route to success for your ecommerce business on Shopify. Maximize the functionality of this powerful platform with assistance from world-class designers and expert-level developers who can bring your vision to life. Make each page on your website an accurate representation of your brand, optimized for results.</p>
                    </div>
                    <div className='Shofity-first-box-part'>
                        <h3>Theme Customization</h3>
                        <p>Unleash the true potential of your website by customizing its theme to suit the needs of your customers. Our Shopify design and development experts know exactly how to match your theme with the emotion your brand hopes to capture. Increase flexibility and separate yourself from competitors with a unique first impression each time users visit.</p>
                    </div>
                    <div className='Shofity-first-box-part'>
                        <h3>App Integrations</h3>
                        <p>Installing applications can happen with the click of a button, but monitoring compatibility between different apps and your website theme takes expertise. Our experience working with Shopify allows us to easily troubleshoot issues we’ve come across before, or build workarounds to implement the apps you want to add.</p>
                    </div>
                    <div className='Shofity-first-box-part'>
                        <h3>Ongoing Support</h3>
                        <p>Once your website is launched, the journey is far from over. Coalition Technologies is here for continued development and support whenever your team needs it. Whether it be backend maintenance, advice on integrations, or direction for your next big marketing campaign, our Shopify services extend way beyond initial setup.</p>
                    </div>
                </div>
            </div>
            <div className='container'>
                <div className='Shopify-four-title-part'>
                    <h3>Why Choose Shopify?</h3>
                    <p>An ecommerce solution that can handle volume and doesn’t intimidate.</p>
                </div>
                <div className='Shopify-four-flex-part'>
                    <div className='Shopify-checkbox-part'>
                        <li><FaCheckCircle />Flexible ecommerce system that can be managed via smartphone</li>
                        <li><FaCheckCircle />Stable mobile-friendly website themes</li>
                        <li><FaCheckCircle />Powerful Shopify shipping solutions</li>
                        <li><FaCheckCircle />Unlimited products & bandwidth</li>
                    </div>
                    <div className='Shopify-checkbox-part'>
                        <li><FaCheckCircle />Flexible ecommerce system that can be managed via smartphone</li>
                        <li><FaCheckCircle />Stable mobile-friendly website themes</li>
                        <li><FaCheckCircle />Powerful Shopify shipping solutions</li>
                        <li><FaCheckCircle />Unlimited products & bandwidth</li>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    )
}
export default ShopifywebsitedevelopmentservicesinUSA;