import Navbar from '../components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../components/Footer'
const Wixwebsitedevelopmentservicesinusa = () => {
    return (
        <>
            <Navbar />
            <title> Wix Website Development Services Company in USA</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="googlebot" content="noindex" />
            <meta key="robots" content="noindex" />
            <div className='Wix-first-image-part'>
                <div className='container'>
                    <div className='Wix-first-flex-part'>
                        <div className='Next-first-title-part'>
                            <h1>Wix Development </h1>
                        </div>
                        <div className='Wix-form-color-part'>
                            <div className='Wix-form-part'>
                                <h2>Quick Contact</h2>
                                <div className='Wix-form'>
                                    <input type="text" placeholder='Name*' /><br />
                                    <input type="email" placeholder='Email*' /><br />
                                    <input type="text" placeholder='Number*' /><br />
                                    <textarea type="text" placeholder='Message*' />
                                    <div className='Next-button'>
                                        <button>Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    )
}
export default Wixwebsitedevelopmentservicesinusa;