import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { BiCheckCircle } from "react-icons/bi";
const Wordpresswebsitedevelopmentservicesinusa = () => {
    return (
        <>
            <Navbar />
            <Head>
                <title>WordpresswebDevelopment website development services company in USA</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="googlebot" content="noindex" />
                <meta key="robots" content="noindex" />
            </Head>
            <div className='WordpresswebDevelopment-first-imge-part'>
                <div className='container'>
                    <div className='wordpress-flex-part'>
                        <div className='WordpresswebDevelopment-title-part'>
                            <h1>Wordpress Web Development</h1>
                        </div>
                        <div className='Wordpressweb-form-color-part'>
                            <div className='Wordpress-form-part'>
                                <h2>Quick Contact</h2>
                                <div className='wordpress-form'>
                                    <input type="text" placeholder='Name*' /><br />
                                    <input type="email" placeholder='Email*' /><br />
                                    <input type="text" placeholder='Number*' /><br />
                                    <textarea type="text" placeholder='Message*' />
                                    <div className='wordpess-button'>
                                        <button>Submit</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className='container'>
                <div className='Wordpress-web-flex-part-'>
                    <div className='wordpress-web-first-part'>
                        <h3>Website Development Services</h3>
                        <h2>Web Development Company in USA</h2>
                        <div className='wordpress-web'>
                            <p className='border'></p>
                            <p>A website design is a dominant element that adds credibility to your business and we provide custom websites with a better user experience. With a solid foundation for more than 13 years, we have been the pioneers among the top web development companies in USA, expertise in delivering innovative solutions to all digital challenges. Our consistency and growth in the industry steered us to more than 100 successfully accomplished projects for our happy clients from the USA, India, and UAE.
                            </p>
                            <p>We are specialized in Custom software development, Mobile app development, eCommerce Development, enterprise solution, Search Engine Optimization(SEO), internet marketing, Content Management System(CMS), and responsive web development. IPIX Tech Services Pvt Ltd is one of the best web development companies in USA, where you’ll get a peerless web solution to climb up the target market making your business great.</p>
                        </div>
                    </div>
                    <div className='Wordpress-web-image-part'>
                        <Image src="/development.jpeg" width="300" height="200" alt="development" />
                    </div>
                </div>
            </div>
            <div className='Wordress-color-first-part'>
                <div className='container'>
                    <div className='Wordress-Choose-part'>
                        <h2>Why Choose Wordpress?</h2>
                        <p>Wordpress is an incredibly popular content management platform  that has been around for nearly two decades. It evolves and innovates as the world and the internet changes to ensure you have plenty of options to personalize your website. With thousands of plug-ins, custom templates, and analytics tools, you can completely customize your website</p>
                    </div>
                    <div className='Wordpress-Choose-flex-part'>
                        <div className='Wordpress-Chosse-imge-part'>
                            <Image src="/Choose.webp" width="300" height="100" alt='Choose' />
                        </div>
                        <div className='Wordpress-Chosse-title-part'>
                            <p>Some of the top reasons the team at Coalition Technologies recommends WordPress for lead generation web design include:</p>
                            <ul>
                                <li><BiCheckCircle /><strong>Tons of Opt-In Options:</strong>  With WordPress, you can select from a variety of opt-in plugins that allow you to optimize for conversions with lightbox popups, scroll boxes, full-screen welcome mats, and floating bars.</li>
                                <li><BiCheckCircle /><strong>Streamlined Targeting:</strong>  Instead of bombarding your website visitors with pop-ups that interrupt their browsing, you can control exactly when your opt-in and form boxes make an appearance.</li>
                                <li><BiCheckCircle /><strong>Simplified Integration:</strong> You don’t want to struggle to integrate lead generation solutions into your marketing strategy. With WordPress, it’s effortless to ensure your website easily merges with all major email marketing services.</li>
                                <p>At Coalition Technologies, we can improve upon an existing WordPress website or help you migrate from an alternative platform. If you think WordPress is the ideal choice for your business needs, our team is here with focused solutions.</p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div className='container'>
                <div className='Wordpress-Development-flex-part'>
                    <div className='Wordpress-Development-title-part'>
                        <h3>Wordpress Website Development</h3>
                        <p>Wordpress is a free, open-source website creation platform. Technically, it is a content management system (CMS) written in PHP using MySQL database. Compared to other platforms, WordPress is the easiest and most powerful blogging and website builder. WordPress websites are known for their standard compliance and high-quality coding. So that it creates remarkable changes in search engines. This is one of the reasons why WordPress sites tend to achieve higher ranks in search engines when compared to others.</p>
                    </div>
                    <div className='Wordpress-Development-images-part'>
                        <Image src="/wordpress.jpg" width="350" height="200" alt="wordpress" />
                        <div className='Wordpress-Development-second-image-part'>
                            <Image src="/wordpressDevelp.jpg" width="350" height="200" alt="wordpress" />
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    )
}
export default Wordpresswebsitedevelopmentservicesinusa;